apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: devsecops-prod
  labels:
    app: file-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: file-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: DATABASE_URL

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: file-service-go-secret
                  key: MINIO_ENDPOINT
            - name: MINIO_PUBLIC_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: file-service-go-secret
                  key: MINIO_PUBLIC_ENDPOINT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: file-service-go-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: file-service-go-secret
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: file-service-go-secret
                  key: MINIO_BUCKET
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          volumeMounts:
            - name: uploads
              mountPath: /tmp/uploads
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: uploads
          emptyDir: {}
        - name: tmp
          emptyDir: {}