apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: devsecops-prod
  labels:
    app: auth-service
    monitored: "true"
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
