apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.apiPort }}
    targetPort: {{ .Values.service.apiPort }}
    name: api
  - port: {{ .Values.service.consolePort }}
    targetPort: {{ .Values.service.consolePort }}
    name: console
  selector:
    app: {{ .Release.Name }}