---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: devsecops-prod
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-sa
  namespace: devsecops-prod
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-service-sa
  namespace: devsecops-prod
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: devsecops-prod
automountServiceAccountToken: false
