apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway
  namespace: devsecops-prod
spec:
  host: gateway.apps.cluster.linsoft.local
  to:
    kind: Service
    name: gateway
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
