apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: devsecops-prod
data:
  default.conf: |
    server_tokens off;
    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/m;

    server {
        listen 80;
        server_name _;

        resolver kube-dns.kube-system.svc.cluster.local valid=5s ipv6=off;

        limit_req zone=api burst=10 nodelay;

        add_header X-Frame-Options         "DENY"                            always;
        add_header X-Content-Type-Options  "nosniff"                         always;
        add_header X-XSS-Protection        "1; mode=block"                   always;
        add_header Referrer-Policy         "strict-origin-when-cross-origin" always;

        location /auth/ {
            set $auth http://auth-service.devsecops-prod.svc.cluster.local:8001;
            proxy_pass $auth;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /items {
            set $app http://app-service.devsecops-prod.svc.cluster.local:8002;
            proxy_pass $app;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        # Routes file-service Go (nouvelles routes)
        location /files/ {
            set $file http://file-service.devsecops-prod.svc.cluster.local:8003;
            proxy_pass $file;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            client_max_body_size 500m;
        }

        location /share {
            set $file http://file-service.devsecops-prod.svc.cluster.local:8003;
            proxy_pass $file;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /download/ {
            set $file http://file-service.devsecops-prod.svc.cluster.local:8003;
            proxy_pass $file;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        # Route legacy upload (garde compatibilité)
        location /upload {
            set $file http://file-service.devsecops-prod.svc.cluster.local:8003;
            proxy_pass $file;
            proxy_set_header Authorization $http_authorization;
            client_max_body_size 10m;
        }

        location /health {
            add_header X-Frame-Options         "DENY"                            always;
            add_header X-Content-Type-Options  "nosniff"                         always;
            add_header X-XSS-Protection        "1; mode=block"                   always;
            add_header Referrer-Policy         "strict-origin-when-cross-origin" always;
            add_header Content-Type            "application/json";
            return 200 '{"status":"ok","service":"gateway"}';
        }
    }
