apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: minio
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.rootUser | quote }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.rootPassword | quote }}
        ports:
        - containerPort: {{ .Values.service.apiPort }}
          name: api
        - containerPort: {{ .Values.service.consolePort }}
          name: console
        resources:
          {{- toYaml .Values.resources | nindent 10 }}