apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: devsecops-prod
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  rootUser: {{ .Values.rootUser | quote }}
  rootPassword: {{ .Values.rootPassword | quote }}