apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-app-service
  namespace: devsecops-prod
spec:
  podSelector:
    matchLabels:
      app: app-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gateway
      ports:
        - port: 8002
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: app-db
      ports:
        - port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
      ports:
        - port: 5353
          protocol: UDP
        - port: 5353
          protocol: TCP