apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-file-service
  namespace: devsecops-prod
spec:
  podSelector:
    matchLabels:
      app: file-service-go
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gateway
    ports:
    - protocol: TCP
      port: 8003
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-dns
      ports:
        - protocol: UDP
          port: 5353
        - protocol: TCP
          port: 5353
    - to:
        - podSelector:
            matchLabels:
              app: minio
      ports:
        - protocol: TCP
          port: 9000
    - to:
        - podSelector:
            matchLabels:
              app: app-db
      ports:
        - protocol: TCP
          port: 5432