apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservices-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - devsecops-prod
  selector:
    matchLabels:
      monitored: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
