apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devsecops-prod
  labels:
    app: app-service
    monitored: "true"
spec:
  selector:
    app: app-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  type: ClusterIP
