replicaCount: 1

image:
  repository: minio/minio
  tag: RELEASE.2024-12-18T13-15-44Z
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  apiPort: 9000
  consolePort: 9001

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"